apiVersion: apps/v1
kind: Deployment
metadata:
  name: doks-debug
  namespace: kube-system
  labels:
    app: doks-debug
spec:
  replicas: 1
  selector:
    matchLabels:
      name: doks-debug
  template:
    metadata:
      labels:
        name: doks-debug
    spec:
      containers:
      - name: doks-debug
        securityContext:
          privileged: true
        image: digitalocean/doks-debug:latest
        command: [ "sleep", "infinity" ]
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "32Mi"
            cpu: "100m"
        volumeMounts:
          - name: host
            mountPath: /host
          - name: docker
            mountPath: /var/run/docker.sock
      priorityClassName: system-cluster-critical
      volumes:
        - name: host
          hostPath:
            path: /
        - name: docker
          hostPath:
            path: /var/run/docker.sock
            type: Socket
